## Now in this we will be using the inbuilt methods of storing chat historires 
## SystemMessages: these messages are the ones which help in assigning the roles eg "you are a profesional bank woker"
## HumanMessages: messages given user
## AiMessages: messages generated by the user 

## for this we require two files 
## "messages.py" and this "chatbot_lc_inbuilt_chathistory.py"

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from dotenv import load_dotenv
import os

load_dotenv() ## loading the environemnt varibles
api_key = os.getenv("GOOGLE_API_KEY") ## creating the varibles for api key 
model=ChatGoogleGenerativeAI(model='models/gemini-2.5-flash', google_api_key=api_key) ## loading the model

chat_history=[
    SystemMessage(content="your are a professional assisstant")
]
## list is created which will store the previous conversationof the suer and AI and everytime and this list of chat hostories 
##will also be passed to the ai model thru api thru invoke method


while True:
    user_input=input('You: ')
    chat_history.append(HumanMessage(content=user_input))
    if user_input=='exit':
        break
    result=model.invoke(chat_history) 
    chat_history.append(HumanMessage(content=result))

    print('AI: ', result.content) 
print(chat_history)  